//AUTH

export const LOGIN_PASSWORD_CHANGED = "LOGIN_PASSWORD_CHANGED";
export const LOGIN_EMAIL_CHANGED = "LOGIN_EMAIL_CHANGED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";

export const FETCH_QUIZ_LIST = "FETCH_QUIZ_LIST"
export const FETCH_QUIZ_CATEGORY_LIST = "FETCH_QUIZ_CATEGORY_LIST";
